### PR TITLE
Add files

### PR DESCRIPTION
**Pull request by hazim1093**

### CODE REVIEW

**Comment by stakater-user** [comment]
@hazim1093 Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.release.stakater.com/job/stakater-docker/job/kafka-cli/job/PR-1/1/) has Failed!

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/kafka-cli:2.11-1.0.2-SNAPSHOT-PR-1-2`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/kafka-cli:2.11-1.0.2-SNAPSHOT-PR-1-3`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/kafka-cli:2.11-1.0.2-SNAPSHOT-PR-1-4`

**Review by rasheedamir — APPROVED** [review]

**Pull request merged**
